---
title: "Using the John Conner Package to Downscale SILO Data"
author: "The ToowoombaTrio"
date: "`r Sys.Date()`"
output: rmarkdown::html_vignette
vignette: >
  %\VignetteIndexEntry{Vignette Title}
  %\VignetteEngine{knitr::rmarkdown}
  \usepackage[utf8]{inputenc}
---
  
# Downscale SILO Hourly Data and Visualise Quality of Predictions
  
This document illustrates the usage of the JohnConner R package to downscale
Queensland SILO weather data from daily to hourly and send an e-mail alert to
subscribers, warning them of heat stress to their crop.
  
```{r, fig.width=5, fig.height=5}
  
  library(WINS)
  BoM_SILO_data <- downscale()
  plot_density(BoM_SILO_data)
  
```
  
## Check Error
  
```{r}
  
rmse(BoM_SILO_data[, 3], BoM_SILO_data[, 5])

mae(BoM_SILO_data[, 3], BoM_SILO_data[, 5])

```

## Generate Map of Heat Stress

```{r, fig.width=5, fig.height=6}
library(raster)
library(fields)
library(reshape)
library(readr)

hourlyT <- BoM_SILO_data[, c(1:2, 4:5)]
head(hourlyT)
hourlyT$hour <- substr(hourlyT[, 3], 6, 7)
hourlyT <- subset(hourlyT, hourlyT$JDay == 1)[, -3]

hourlyT <- melt(hourlyT, id.vars = c("station_number", "hour", "JDay"), measure.vars = "SILO_TMP")
hourlyT <- cast(hourlyT, hour~station_number, fun = "mean")

head(QLD_SILO_and_hourly_stations)

header_info <- QLD_SILO_and_hourly_stations[, 2]

# get DEM data for QLD
alt <- raster::getData(name = "alt", country = "Australia", path = "~/Downloads")

# get outline of Australia
Oz <- raster::getData(name = "GADM", download = TRUE, country = "AUS", level = 1)

# Subset Australia data to QLD
QLD <- which(Oz@data$NAME_1 == "Queensland")

# crop and mask altitude data for only QLD
QLD_alt <- raster::crop(alt, QLD)
QLD_alt <- raster::mask(QLD_alt, QLD)

# create the splined surface of temperatures to extract values

for (i in 1:nrow(QLD_df)) {
  tps_spline <- fields::Tps(data.frame(QLD_df$LONGITUDE, QLD_df$LATITUDE, QLD_df$STN_HT),
                            QLD_df$hour_temp, lon.lat = TRUE)
  
  # interpolate thin plate spline object and write to disk
  pred_temp <- interpolate(QLD_alt, tps_spline, xyOnly = FALSE)
  
}

temp_threshold <- 30

hours_of_high_temps <- c()

# for (x in names(hourlyT[, 2:71])) {
#   hours_of_high_temps <- c(hours_of_high_temps, length(hourlyT[, x][hourlyT[, x] > temp_threshold]))
# }
# 
# high_temps <- data.frame(names(hourlyT[, 2:71]), as.numeric(hours_of_high_temps))
# names(high_temps) <- c("station_number", "hours_of_high_temps")
# 
# QLD_df <- plyr::join(high_temps, QLD_SILO_and_hourly_stations, by = "station_number", type = "left")
# head(QLD_df)

```

# Automated e-mails to subscribers

```{r}


# send email abut specific locations
our_email <- "toowoombatrio@gmail.com"
attachmentName <- "QLDmap.png"
#subscribers details

library(mailR)

for (value in subscribers$run) {
  email <- as.character(subscribers[value, 1])
  location <- as.character(subscribers[value, 2])
  lat <- as.numeric(subscribers[value, 3])
  lon <- as.numeric(subscribers[value, 4])
  hours_of_heat_stress <- as.character(round(predict(spline, cbind(lat, lon)),0))
  body_text <- paste("Hello from the Toowoomba Trio Your crops at",
                     location, "recieved",
                     hours_of_heat_stress,
                     "hours of heat stress yesterday")
  
  sender <- our_email
  recipients <- email
  send.mail(from = sender,
            to = recipients,
            subject = "Hours of heat stress yesterday",
            body = body_text,
            attach.files = attachmentName,
            smtp = list(host.name = "smtp.gmail.com", port = 465, 
                        user.name = "toowoombatrio@gmail.com",
                        passwd = "", ssl = TRUE),
            authenticate = TRUE,
            send = TRUE)
  
}

```